services:
  api:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync
          path: .
          target: ./
  postgres :
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  qdrant:
    image: "qdrant/qdrant"
    ports:
      - "6333:6333"