services:
  api:
    build: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATASE: ${POSTGRES_DATASE}
      QDRANT_URL: ${QDRANT_URL}
    ports:
      - "8080:80"
    develop:
      watch:
        - action: sync+restart
          path: .
          target: ./code
  postgres :
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  qdrant:
    image: "qdrant/qdrant"
    ports:
      - "6333:6333"
  webchat:
    build: ./web/chat
    ports:
      - "80:3000"
    develop:
      watch:
        - action: sync+restart
          path: ./web/chat
          target: /usr/src/app